### ISSUE TITLE
CMPlan(ước tính chi phí)

### ISSUE THREAD

**Issue by Buckypro** [Buckypro/OKA2-HV#7]

**Comment by hloc1312** [comment]
[plan_hotel_voucher.xlsx](https://github.com/Buckypro/OKA2-HV/files/6348946/plan_hotel_voucher.xlsx)

**Comment by Buckypro** [comment]
[Uploading CMPlan-OKA2-HV.docx…]()

**Comment by Buckypro** [comment]
[Uploading CMPlan-OKA2-HV.docx…]()

**Comment by Buckypro** [comment]
[CMPlan-OKA2-HV.docx](https://github.com/Buckypro/OKA2-HV/files/6444896/CMPlan-OKA2-HV.docx)
